---
version: "3"
services:
  node:
    build:
      context: .
      args:
        - arch=${ARCH:-x86_64}
    command: ./setup_and_run.sh echofi16g2rahf5846rxzp3fwlswy08fz8ccuwk7lqjk2 echofi1w7f3xx7e75p4l7qdym5msqem9rd4dyc4egldw6
    ports:
      - 1317:1317 # rest
      - 26656:26656 # p2p
      - 26657:26657 # rpc
    environment:
      - GAS_LIMIT=${GAS_LIMIT:-10000000}
      - STAKE_TOKEN=${STAKE_TOKEN:-uecho}
      - TIMEOUT_COMMIT=${TIMEOUT_COMMIT:-5s}
      - UNSAFE_CORS=true
